name: 'Maximize build space'
description: maximize build space
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: df -h

    - name: Remove unused packages
      shell: bash
      run: |
        sudo apt-get remove -y --purge powershell --fix-missing || true
        sudo apt-get remove -y --purge '^snapd.*' || true
        sudo apt-get remove -y --purge '^aspnetcore-.*' || true
        sudo apt-get remove -y --purge '^dotnet-.*' || true
        sudo apt-get remove -y --purge '^llvm-.*' || true
        sudo apt-get remove -y --purge '^clang-.*' || true
        sudo apt-get remove -y --purge 'php.*' || true
        sudo apt-get remove -y --purge '^mongodb-.*' || true
        sudo apt-get remove -y --purge '^mysql-.*' || true
        sudo apt-get remove -y --purge '^postgresql-.*' || true
        sudo apt-get remove -y --purge '^temurin.*' || true
        sudo apt-get remove -y --purge '^r-base.*' || true
        sudo apt-get remove -y --purge '^mono.*' || true
        sudo apt-get remove -y --purge '^lld.*' || true
        sudo apt-get remove -y --purge '^gfortran.*' || true
        sudo apt-get remove -y --purge '^mercurial.*' || true      
        sudo apt-get remove -y --purge '^apache2.*' || true
        sudo apt-get remove -y --purge '^byobu.*' || true
        sudo apt-get remove -y --purge '^cloud-.*' || true        
        sudo apt-get remove -y --purge '^imagemagick.*' || true
        sudo apt-get remove -y --purge '^nginx.*' || true
        sudo apt-get remove -y --purge '^ruby.*' || true
        sudo apt-get remove -y --purge '^swig.*' || true
        sudo apt-get remove -y --purge '^tk.*' || true
        sudo apt-get remove -y --purge '^tcl.*' || true          
        sudo apt-get remove -y --purge '^ubuntu-pro.*' || true  
        sudo apt-get remove -y --purge '^linux-headers.*' || true   
        sudo apt-get remove -y --purge '^mssql.*' || true          
        sudo apt-get remove -y --purge '?name(^gcc-.*) ?and(?not(?name(^gcc-14.*))) ?and(?not(?name(^gcc-13.*)))' || true
        sudo apt-get remove -y --purge '?name(^g\+\+.-*) ?and(?not(?name(^g\+\+-14.*))) ?and(?not(?name(^g\+\+-13.*)))' || true
        sudo apt-get remove -y --purge '?name(^cpp-.*) ?and(?not(?name(^cpp-14.*))) ?and(?not(?name(^cpp-13.*)))' || true                    
        sudo apt-get remove -y --purge '^fonts-.*' || true     
        # sudo apt-get remove -y --purge google-chrome-stable microsoft-edge-stable || true
        # sudo apt-get remove -y --purge google-cloud-cli --fix-missing || true        
        sudo apt-get remove -y --purge azure-cli firefox mono-devel libgl1-mesa-dri --fix-missing || true
        
        sudo rm -Rf /usr/libexec/docker
        sudo rm -Rf /usr/share/php
        sudo rm -Rf /etc/php/8.3/mods-available
        sudo rm -Rf /etc/mysql
        sudo rm -Rf /var/lib/apache2
        sudo rm -Rf /var/www/html
        sudo rm -Rf /etc/cloud/cloud.cfg.d
        sudo rm -Rf /var/lib/gems/3.2.0
        sudo rm -Rf /var/lib/update-manager
        sudo rm -Rf /etc/firefox
        sudo rm -Rf /etc/apport/native-origins.d
        sudo rm -Rf /etc/apport/blacklist.d
        sudo rm -Rf /usr/local/share/man
        sudo rm -Rf /opt/az        

    - name: Install necessary packages
      shell: bash
      run: |
        sudo apt update
        sudo apt -y install gcc make git unzip wget xz-utils bc gperf zip g++ xfonts-utils xsltproc openjdk-11-jre-headless libxml-parser-perl lzop libjson-parse-perl libjson-perl \
              libparse-yapp-perl libncurses5-dev bc bzip2 diffutils gawk gcc gperf gzip file patchutils lzop make patch perl sed tar unzip wget xz-utils zip zstd \
              libncurses5-dev libc6-dev libparse-yapp-perl libxml-parser-perl qemu-user-binfmt g++ xfonts-utils xsltproc rdfind libc6-amd64-cross libglib2.0-0 \
              libelf-dev elfutils

        sudo snap remove $(snap list | awk '!/^Name|^core|^snapd/ {print $1}') || true
        sudo apt -y --purge purge snapd || true
        sudo apt -y --purge autoremove
        sudo apt clean

    - name: clean apt
      shell: bash
      run: |
        sudo apt purge '~c'
        sudo apt-get autoremove -y
        sudo apt clean

    - name: Remove Hosted Tool Cache
      shell: bash
      run: |
        sudo rm -rf /opt/hostedtoolcache

    - name: Remove Go
      shell: bash
      run: |
        sudo rm -rf /opt/hostedtoolcache/go

    - name: Remove CodeQL
      shell: bash
      run: |
        sudo rm -rf /opt/hostedtoolcache/CodeQL

    - name: Remove PowerShell
      shell: bash
      run: |
        sudo rm -rf /usr/local/share/powershell

    - name: Remove Android SDK
      shell: bash
      run: |
        sudo rm -rf /usr/local/lib/android

    - name: Remove Haskell GHC
      shell: bash
      run: |
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup/ghc

    - name: Remove Swift
      shell: bash
      run: |
        sudo rm -rf /usr/share/swift

    - name: Remove .NET
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet

    - name: Remove az
      shell: bash
      run: |
        sudo rm -rf /opt/az

    - name: Remove Docker images
      shell: bash
      run: |
        sudo docker image prune --all --force
        sudo apt-get remove -y --purge '^docker-ce.*'          

    - name: Remove Agent tools directory
      shell: bash
      run: |
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Remove other directories
      shell: bash
      run: |
        sudo rm -rf /etc/mono
        sudo rm -rf /imagegeneration

    - name: List packages
      shell: bash
      run: sudo dpkg -l

    - name: Disk space report after modification
      shell: bash
      run: |
        df -h