name: 'Maximize build space'
description: maximize build space
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: df -h

    - name: Preinstall packages
      shell: bash
      run: |
        sudo apt update
        sudo apt install eatmydata aptitude shim-signed
        sudo ln -s /usr/lib/x86_64-linux-gnu/libeatmydata.so /usr/lib/libeatmydata.so

    - name: Remove all packages which are not in important or required
      shell: bash
      run: |
        echo "Remove shim-signed"
        sudo apt remove --purge --allow-remove-essential shim-signed 
        
        echo "Remove snapd"
        sudo systemctl disable snapd || true
        sudo snap remove $(snap list | awk '!/^Name|^core|^snapd/ {print $1}') || true          
        sudo eatmydata apt -y --purge purge snapd || true          
        
        echo "Remove docker images"
        docker system prune -af || true
        docker builder prune -af || true
        
        echo "Remove non-important packages"
        TOREMOVE=$(aptitude search '~i!~M!~prequired!~pimportant!~R~prequired!~R~R~prequired!~R~pimportant!~R~R~pimportant!initramfs-tools!eatmydata' | awk '{print $2}')
        echo "Remove Packages $TOREMOVE"
        
        sudo eatmydata apt -y purge $(aptitude search '~i!~M!~prequired!~pimportant!~R~prequired!~R~R~prequired!~R~pimportant!~R~R~pimportant!initramfs-tools!eatmydata' | awk '{print $2}')
        
        echo "Autoremove"
        sudo eatmydata apt -y --purge autoremove
        
        echo "Remove some directories"
        sudo rm -rf /var/lib/gems/3.2.0 /usr/libexec/docker /etc/needrestart/conf.d \
                    /etc/cloud/cloud.cfg.d /etc/ssh/sshd_config.d /usr/share/php \
                    /lib/systemd/user-generators /lib/systemd/user /usr/local/share/man \
                    /usr/lib/systemd/system-sleep /usr/lib/systemd/system-shutdown /etc/php/8.3/mods-available \
                    /lib/modules/6.11.0-1018-azure /usr/share/az_12.5.0 /usr/share/miniconda \
                    /usr/local/aws-cli /usr/share/kotlinc /home/runner/.dotnet /home/packer/.dotnet \
                    /etc/skel/.dotnet /usr/local/man/ /usr/local/share/chromedriver-linux64 \
                    /home/runner/.rustup /home/linuxbrew /usr/share/java /home/runner/.cargo \
                    /var/lib/mysql /var/lib/waagent
        
        echo "Remove .NET SDKs"
        sudo rm -rf /usr/share/dotnet
        
        echo "Remove Swift toolchain"
        sudo rm -rf /usr/share/swift
        
        echo "Remove Haskell (GHC)"
        sudo rm -rf /usr/local/.ghcup
        
        echo "Remove Julia"
        sudo rm -rf /usr/local/julia*
        
        echo "Remove Android SDKs"
        sudo rm -rf /usr/local/lib/android
        
        echo "Remove Chromium"
        sudo rm -rf /usr/local/share/chromium
        
        echo "Remove Microsoft/Edge and Google Chrome builds"
        sudo rm -rf /opt/microsoft /opt/google
        
        echo "Remove Azure CLI"
        sudo rm -rf /opt/az          
        
        echo "Remove PowerShell"
        sudo rm -rf /usr/local/share/powershell
        
        echo "Remove CodeQL and other toolcaches"
        sudo rm -rf /opt/hostedtoolcache

    - name: Disk space report after modification
      shell: bash
      run: |
        df -h